# Generated by Django 4.2.3 on 2024-01-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('ultimo_login', models.DateTimeField(auto_now=True)),
                ('roles', models.CharField(choices=[('personal', 'Personal'), ('empresa', 'Empresa')], default='personal', max_length=8)),
            ],
        ),
    ]
