# Generated by Django 4.2.3 on 2024-02-08 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticated', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_usuario',
            new_name='password',
        ),
    ]
